on: push
defaults:
  run:
    shell: arch -arm64 bash --noprofile --norc -eo pipefail {0}
jobs:
  testit:
    name: Test Job for M1 runner
    runs-on: self-hosted
    steps:
    - name: clone repo
      uses: actions/checkout@v2

    - name: do stuff default
      run: |
        arch
        zsh -c 'echo hi mom from $(arch)'
        python3 -V
        pwd
        ls -la

    - name: do stuff forced arm64
      run: |
        arch -arm64 zsh -c 'echo hi mom from $(arch)'

