on: [push, workflow_dispatch]
jobs:
  testit:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
    - name: poke at it
      run: |
        python3 -m pip install ansible-core
        ansible localhost -m setup
  
